---
- name: Host Prerequisites
  hosts: zookeeper:kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.common
      tags: common

- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.kafka_broker
