---
- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: client.sasl.jaas.config
        expected_value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafka_rest\" password=\"kafka_rest-secret\";'
