---
- name: Export Error Logs
  shell: "journalctl -u {{service_name}} --since -10m > /tmp/{{service_name}}.log"

- name: Fetch Files for Investigation
  fetch:
    src: "{{item}}"
    dest: "error_files/{{inventory_hostname}}-{{item|basename}}"
    flat: true
    fail_on_missing: false
  loop:
    - "{{config_file}}"
    - "/tmp/{{service_name}}.log"

- name: Fail Installation
  fail:
    msg: Health checks failed. Review log and property files in error_files/ directory
