---
- name: Create Secrets Protection Directory
  file:
    path: "{{ confluent_ssl }}/private/"
    state: directory
    mode: 0755

- name: Copy security.properties file to Host
  copy:
    src: "{{ secrets_protection_security_file }}"
    dest: "{{ confluent_ssl }}/private/security.properties"

- name: Encrypt All Properties that Contain 'password'
  shell: |
    {{ confluent_cli_path }} secret file encrypt --config-file {{ config_path }} \
      --local-secrets-file "{{ confluent_ssl }}/private/security.properties" \
      --remote-secrets-file "{{ confluent_ssl }}/private/security.properties"
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: encrypt_passwords|bool

- name: Encrypt Selected Properties
  shell: |
    {{ confluent_cli_path }} secret file encrypt --config-file {{ config_path }} \
      --local-secrets-file "{{ confluent_ssl }}/private/security.properties" \
      --remote-secrets-file "{{ confluent_ssl }}/private/security.properties" \
      --config {{ item }}
  loop: "{{ properties }}"
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: properties|length>0
