---
- name: Check if Kafka Service Running
  shell: "systemctl show -p SubState {{kafka_broker_service_name}}"
  changed_when: false
  check_mode: false
  register: substate

- name: Parallel Restart
  include: restart.yml
  when: substate.stdout != 'SubState=running' or certs_updated|bool or not kafka_broker_jolokia_enabled|bool

- name: Ordered Restart
  include: ordered_restart.yml
  when: substate.stdout == 'SubState=running' and not certs_updated|bool and kafka_broker_jolokia_enabled|bool
