---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

- name: Gather OS Facts
  setup:
    # Only gathers items in list, filters out the rest
    filter: "{{item}}"
    gather_subset:
      - '!all'
  loop:
    - ansible_os_family
    - ansible_fqdn

# Install Packages
- name: Install the KSQL Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{ksql_packages}}"
  when:
    - ansible_os_family == "RedHat"
    - installation_method == "package"

- name: Install the KSQL Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{ksql_packages}}"
  when:
    - ansible_os_family == "Debian"
    - installation_method == "package"

# Configure environment
- name: Create Ksql Group
  group:
    name: "{{ksql_group}}"
    gid: "{{ksql_group_gid}}"

- name: Create Ksql User
  user:
    name: "{{ksql_user}}"
    uid: "{{ksql_user_uid}}"
    comment: "Connect Distributed User"
    system: true
    group: "{{ksql_group}}"

- name: Create profile
  blockinfile:
    path: '/home/{{ ksql_user }}/.bash_profile'
    block: |
      # User specific environment and startup programs
      JAVA_HOME={{ confluent_jdk }}/{{ confluent_jdk_version }}
      JAVA=${JAVA_HOME}/bin/java
      HOME_CONFLUENT={{archive_destination_path}}/confluent-{{confluent_package_version}}
      PATH=$HOME_CONFLUENT/bin:/opt/java/bin:$PATH
      export JAVA_HOME JAVA HOME_CONFLUENT PATH
  become_user: "{{ ksql_user }}"

- name: update ulimits
  blockinfile:
    path: /etc/security/limits.conf
    marker_begin : "<!-- BEGIN {{ksql_user}} ANSIBLE MANAGED BLOCK -->"
    marker_end : "<!-- END {{ksql_user}} ANSIBLE MANAGED BLOCK -->"
    insertafter: EOF
    block: |
      {{ ksql_user }} hard core 0
      {{ ksql_user }} soft nofile 65535
      {{ ksql_user }} hard nofile 65535
      {{ ksql_user }} soft nproc 4096
      {{ ksql_user }} hard nproc 16384

- name: Set Ksql streams dir permissions
  file:
    path: "{{ksql_final_properties['ksql.streams.state.dir']}}"
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
    state: directory
    mode: 0750

# Archive File deployments need to create SystemD service units
# Copy the tarball's systemd service to the system
- name: Copy Ksql Service from archive file to system
  copy:
    src: "{{binary_base_path}}/lib/systemd/system/{{ksql.systemd_file|basename}}"
    remote_src: true
    dest: "{{ksql.systemd_file}}"
    mode: 0644
    force: true
  when: installation_method == "archive"

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{ksql_truststore_storepass}}"
    truststore_path: "{{ksql_truststore_path}}"
    keystore_path: "{{ksql_keystore_path}}"
    keystore_storepass: "{{ksql_keystore_storepass}}"
    keystore_keypass: "{{ksql_keystore_keypass}}"
    service_name: ksql
    user: "{{ksql_user}}"
    group: "{{ksql_group}}"
    hostnames: "{{ [inventory_hostname, ansible_fqdn] | unique }}"
    ca_cert_path: "{{ksql_ca_cert_path}}"
    cert_path: "{{ksql_cert_path}}"
    key_path: "{{ksql_key_path}}"
  when: >
    ksql_ssl_enabled|bool or
    kafka_broker_listeners[ksql_kafka_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool or
    mds_tls_enabled | bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{ksql_group}}"
    kerberos_user: "{{ksql_user}}"
    kerberos_keytab_path: "{{ksql_kerberos_keytab_path}}"
    kerberos_keytab_destination_path: "{{ksql_keytab_path}}"
    kerberos_handler: "restart ksql"
  when: kafka_broker_listeners[ksql_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Copy Custom KSQL Files
  include_tasks: ../../tasks/copy_files.yml
  vars:
    copy_files: "{{ksql_copy_files}}"
    user: "{{ksql_user}}"
    group: "{{ksql_group}}"
  when: ksql_copy_files | length > 0

- name: Configure RBAC
  include_tasks: rbac.yml
  when: rbac_enabled|bool

- name: Create Ksql Config directory
  file:
    path: "{{ ksql.config_file | dirname }}"
    state: directory
    mode: 0750
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"

- name: Create Ksql Config
  template:
    src: ksql-server.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
  notify:
    - restart ksql

- name: Create Logs Directory
  file:
    path: "{{ksql.appender_log_path}}"
    state: directory
    group: "{{ksql_group}}"
    owner: "{{ksql_user}}"
    mode: 0770

- name: Create log4j Directory
  file:
    path: "{{ksql.log4j_file | dirname}}"
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
    state: directory
    mode: 0750

- name: Create Ksql log4j Config
  template:
    src: ksql-server_log4j.properties.j2
    dest: "{{ksql.log4j_file}}"
    mode: 0640
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
  notify: restart ksql

- name: Enable Secrets Protection
  include_tasks: ../../tasks/secrets_protection.yml
  vars:
    encrypt_passwords: "{{ ksql_secrets_protection_encrypt_passwords }}"
    properties: "{{ ksql_secrets_protection_encrypt_properties }}"
    config_path: "{{ ksql.config_file }}"
  when: ksql_secrets_protection_enabled|bool

- name: Create RocksDB Directory
  file:
    path: "{{ksql_rocksdb_path}}"
    group: "{{ksql_group}}"
    owner: "{{ksql_user}}"
    mode: 0750
    state: directory
  when: ksql_rocksdb_path != ""

- name: Set Permission to RocksDB Files
  file:
    path: "{{ksql_rocksdb_path}}"
    group: "{{ksql_group}}"
    owner: "{{ksql_user}}"
    recurse: true
  when: ksql_rocksdb_path != ""

- name: Deploy JMX Exporter Config File
  copy:
    src: "ksql.yml"
    dest: "{{ksql_jmxexporter_config_path}}"
    mode: 0640
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
  when: ksql_jmxexporter_enabled|bool

- name: Create Service Override Directory
  file:
    path: "{{ksql.systemd_override | dirname}}"
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{ksql.systemd_override}}"
    mode: 0640
    owner: "{{ksql_user}}"
    group: "{{ksql_group}}"
  notify: restart ksql

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart ksql
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Ksql Service
  systemd:
    name: "{{ksql_service_name}}"
    enabled: true
    state: started

- name: Health Check
  include_tasks: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
