---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

- name: Gather OS Facts
  setup:
    # Only gathers items in list, filters out the rest
    filter: "{{item}}"
    gather_subset:
      - '!all'
  loop:
    - ansible_os_family
    - ansible_fqdn

# Install Packages
- name: Install the Schema Registry Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{schema_registry_packages}}"
  when:
    - ansible_os_family == "RedHat"
    - installation_method == "package"

- name: Install the Schema Registry Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{schema_registry_packages}}"
  when:
    - ansible_os_family == "Debian"
    - installation_method == "package"

# Configure environment
- name: Schema Registry Group
  group:
    name: "{{schema_registry_group}}"
    gid: "{{schema_registry_group_gid}}"

- name: Schema Registry User
  user:
    name: "{{schema_registry_user}}"
    uid: "{{schema_registry_user_uid}}"
    comment: "Schema Registry User"
    system: true
    group: "{{schema_registry_group}}"

- name: Create profile
  blockinfile:
    path: '/home/{{ schema_registry_user }}/.bash_profile'
    block: |
      # User specific environment and startup programs
      JAVA_HOME={{ confluent_jdk }}/{{ confluent_jdk_version }}
      JAVA=${JAVA_HOME}/bin/java
      HOME_CONFLUENT={{archive_destination_path}}/confluent-{{confluent_package_version}}
      PATH=$HOME_CONFLUENT/bin:/opt/java/bin:$PATH
      export JAVA_HOME JAVA HOME_CONFLUENT PATH
  become_user: "{{ schema_registry_user }}"

- name: update ulimits
  blockinfile:
    path: /etc/security/limits.conf
    marker_begin : "<!-- BEGIN {{schema_registry_user}} ANSIBLE MANAGED BLOCK -->"
    marker_end : "<!-- END {{schema_registry_user}} ANSIBLE MANAGED BLOCK -->"
    insertafter: EOF
    block: |
      {{ schema_registry_user }} hard core 0
      {{ schema_registry_user }} soft nofile 65535
      {{ schema_registry_user }} hard nofile 65535
      {{ schema_registry_user }} soft nproc 4096
      {{ schema_registry_user }} hard nproc 16384


# Archive File deployments need to create SystemD service units
# Copy the tarball's systemd service to the system
- name: Copy Schema Registry Service from archive file to system
  copy:
    src: "{{binary_base_path}}/lib/systemd/system/{{schema_registry.systemd_file|basename}}"
    remote_src: true
    dest: "{{schema_registry.systemd_file}}"
    mode: 0644
    force: true
  when: installation_method == "archive"

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{schema_registry_truststore_storepass}}"
    truststore_path: "{{schema_registry_truststore_path}}"
    keystore_path: "{{schema_registry_keystore_path}}"
    keystore_storepass: "{{schema_registry_keystore_storepass}}"
    keystore_keypass: "{{schema_registry_keystore_keypass}}"
    service_name: schema_registry
    user: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
    hostnames: "{{ [inventory_hostname, ansible_fqdn] | unique }}"
    ca_cert_path: "{{schema_registry_ca_cert_path}}"
    cert_path: "{{schema_registry_cert_path}}"
    key_path: "{{schema_registry_key_path}}"
  when: >
    schema_registry_ssl_enabled | bool or
    kafka_broker_listeners[schema_registry_kafka_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool or
    mds_tls_enabled | bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{schema_registry_group}}"
    kerberos_user: "{{schema_registry_user}}"
    kerberos_keytab_path: "{{schema_registry_kerberos_keytab_path}}"
    kerberos_keytab_destination_path: "{{schema_registry_keytab_path}}"
    kerberos_handler: "restart schema-registry"
  when: kafka_broker_listeners[schema_registry_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Copy Custom Schema Registry Files
  include_tasks: ../../tasks/copy_files.yml
  vars:
    copy_files: "{{schema_registry_copy_files}}"
    user: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
  when: schema_registry_copy_files | length > 0

- name: Configure RBAC
  include_tasks: rbac.yml
  when: rbac_enabled|bool

- name: Create Schema Registry Config directory
  file:
    path: "{{ schema_registry.config_file | dirname }}"
    state: directory
    mode: 0750
    owner: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"

- name: Create Schema Registry Config
  template:
    src: schema-registry.properties.j2
    dest: "{{schema_registry.config_file}}"
    mode: 0640
    owner: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
  notify: restart schema-registry

- name: Create Logs Directory
  file:
    path: "{{schema_registry.appender_log_path}}"
    state: directory
    group: "{{schema_registry_group}}"
    owner: "{{schema_registry_user}}"
    mode: 0770

- name: Create log4j Directory
  file:
    path: "{{schema_registry.log4j_file | dirname}}"
    owner: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
    state: directory
    mode: 0750

- name: Create Schema Registry log4j Config
  template:
    src: schema_registry_log4j.properties.j2
    dest: "{{schema_registry.log4j_file}}"
    mode: 0640
    owner: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
  notify: restart schema-registry

- name: Enable Secrets Protection
  include_tasks: ../../tasks/secrets_protection.yml
  vars:
    encrypt_passwords: "{{ schema_registry_secrets_protection_encrypt_passwords }}"
    properties: "{{ schema_registry_secrets_protection_encrypt_properties }}"
    config_path: "{{ schema_registry.config_file }}"
  when: schema_registry_secrets_protection_enabled|bool

- name: Deploy JMX Exporter Config File
  copy:
    src: "schema_registry.yml"
    dest: "{{schema_registry_jmxexporter_config_path}}"
    mode: 0640
    owner: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
  when: schema_registry_jmxexporter_enabled|bool

- name: Create Service Override Directory
  file:
    path: "{{schema_registry.systemd_override | dirname}}"
    owner: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{schema_registry.systemd_override}}"
    mode: 0640
    owner: "{{schema_registry_user}}"
    group: "{{schema_registry_group}}"
  notify: restart schema-registry

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart schema-registry
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Schema Registry Service
  systemd:
    name: "{{schema_registry_service_name}}"
    enabled: true
    state: started

- name: Health Check
  include_tasks: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
