---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

- name: Gather OS Facts
  setup:
    # Only gathers items in list, filters out the rest
    filter: "{{item}}"
    gather_subset:
      - '!all'
  loop:
    - ansible_os_family
    - ansible_fqdn

- name: Install the Zookeeper Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{zookeeper_packages}}"
  when:
    - ansible_os_family == "RedHat"
    - installation_method == "package"

- name: Install the Zookeeper Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{zookeeper_packages}}"
  when:
    - ansible_os_family == "Debian"
    - installation_method == "package"

# Configure environment
- name: Create Zookeeper Group
  group:
    name: "{{zookeeper_group}}"
    gid: "{{zookeeper_group_gid}}"

- name: Create Zookeeper User
  user:
    name: "{{zookeeper_user}}"
    uid: "{{zookeeper_user_uid}}"
    comment: "Zookeeper User"
    system: true
    group: "{{zookeeper_group}}"

- name: Create profile
  blockinfile:
    path: '/home/{{ zookeeper_user }}/.bash_profile'
    block: |
      # User specific environment and startup programs
      JAVA_HOME={{ confluent_jdk }}/{{ confluent_jdk_version }}
      JAVA=${JAVA_HOME}/bin/java
      HOME_CONFLUENT={{archive_destination_path}}/confluent-{{confluent_package_version}}
      PATH=$HOME_CONFLUENT/bin:/opt/java/bin:$PATH
      export JAVA_HOME JAVA HOME_CONFLUENT PATH
  become_user: "{{ zookeeper_user }}"

- name: update ulimits
  blockinfile:
    path: /etc/security/limits.conf
    marker_begin : "<!-- BEGIN {{zookeeper_user}} ANSIBLE MANAGED BLOCK -->"
    marker_end : "<!-- END {{zookeeper_user}} ANSIBLE MANAGED BLOCK -->"
    insertafter: EOF
    block: |
      {{ zookeeper_user }} hard core 0
      {{ zookeeper_user }} soft nofile 65535
      {{ zookeeper_user }} hard nofile 65535
      {{ zookeeper_user }} soft nproc 4096
      {{ zookeeper_user }} hard nproc 16384


# Archive File deployments need to create SystemD service units
# Copy the tarball's systemd service to the system
- name: Copy Zookeeper Service from archive file to system
  copy:
    src: "{{binary_base_path}}/lib/systemd/system/{{zookeeper.systemd_file|basename}}"
    remote_src: true
    dest: "{{zookeeper.systemd_file}}"
    mode: 0644
    force: true
  when: installation_method == "archive"

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{zookeeper_truststore_storepass}}"
    truststore_path: "{{zookeeper_truststore_path}}"
    keystore_path: "{{zookeeper_keystore_path}}"
    keystore_storepass: "{{zookeeper_keystore_storepass}}"
    keystore_keypass: "{{zookeeper_keystore_keypass}}"
    service_name: zookeeper
    user: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
    hostnames: "{{ [inventory_hostname, ansible_fqdn] | unique }}"
    ca_cert_path: "{{zookeeper_ca_cert_path}}"
    cert_path: "{{zookeeper_cert_path}}"
    key_path: "{{zookeeper_key_path}}"
  when: zookeeper_ssl_enabled|bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{zookeeper_group}}"
    kerberos_user: "{{zookeeper_user}}"
    kerberos_keytab_path: "{{zookeeper_kerberos_keytab_path}}"
    kerberos_keytab_destination_path: "{{zookeeper_keytab_path}}"
    kerberos_handler: "restart zookeeper"
  when: zookeeper_sasl_protocol == 'kerberos'

- name: Copy Custom Zookeeper Files
  include_tasks: ../../tasks/copy_files.yml
  vars:
    copy_files: "{{zookeeper_copy_files}}"
    user: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
  when: zookeeper_copy_files | length > 0

- name: Set Zookeeper dataDir ownership
  file:
    path: "{{zookeeper_final_properties.dataDir}}"
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
    state: directory
    mode: 0750

- name: Set Ownership of Data Dir files
  file:
    path: "{{zookeeper_final_properties.dataDir}}"
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
    recurse: true

- name: Create Zookeeper myid File
  template:
    src: myid.j2
    dest: "{{zookeeper_final_properties.dataDir}}/myid"
    mode: 0640
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"

- name: Create Zookeeper Config directory
  file:
    path: "{{ zookeeper.config_file | dirname }}"
    state: directory
    mode: 0750
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"

- name: Create Zookeeper Config
  template:
    src: zookeeper.properties.j2
    dest: "{{zookeeper.config_file}}"
    mode: 0640
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
  register: zookeeper_config
  notify: restart zookeeper

- name: Create Log Directory
  file:
    path: "{{zookeeper.log_path}}"
    state: directory
    group: "{{zookeeper_group}}"
    owner: "{{zookeeper_user}}"
    mode: 0770

- name: Create log4j Directory
  file:
    path: "{{zookeeper.log4j_file | dirname}}"
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
    state: directory
    mode: 0750

- name: Create Zookeeper log4j config
  template:
    src: zookeeper_log4j.properties.j2
    dest: "{{zookeeper.log4j_file}}"
    mode: 0640
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
  notify: restart zookeeper

- name: Create Zookeeper Jaas config
  template:
    src: zookeeper_jaas.conf.j2
    dest: "{{zookeeper.jaas_file}}"
    mode: 0640
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
  when: zookeeper_sasl_protocol in ['kerberos', 'digest']
  notify: restart zookeeper

- name: Deploy JMX Exporter Config File
  copy:
    src: "zookeeper.yml"
    dest: "{{zookeeper_jmxexporter_config_path}}"
    mode: 0640
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
  when: zookeeper_jmxexporter_enabled|bool

- name: Enable Secrets Protection
  include_tasks: ../../tasks/secrets_protection.yml
  vars:
    encrypt_passwords: "{{ zookeeper_secrets_protection_encrypt_passwords }}"
    properties: "{{ zookeeper_secrets_protection_encrypt_properties }}"
    config_path: "{{ zookeeper.config_file }}"
  when: zookeeper_secrets_protection_enabled|bool

- name: Create Service Override Directory
  file:
    path: "{{zookeeper.systemd_override | dirname}}"
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{zookeeper.systemd_override}}"
    mode: 0640
    owner: "{{zookeeper_user}}"
    group: "{{zookeeper_group}}"
  notify: restart zookeeper

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart zookeeper
  when: certs_updated|bool

- meta: flush_handlers

- name: Zookeeper Service Started
  systemd:
    name: "{{zookeeper_service_name}}"
    enabled: true
    state: started

- name: Zookeeper Health Check
  include: health_check.yml
  when:
    - health_checks_enabled|bool
    - not ansible_check_mode
